### ISSUE TITLE
Option to generate n different batches.tfrecord files with preprocess

### ISSUE THREAD

**Issue by dbaumgarten** [dbaumgarten/FToDTF#33]
Currently fasttext preprocess produces a single file containing all training-samples. This way all workers of the cluster would work on the same cluster and the distribution would be completely useless.

Add option to tensorflow preprocess to slit the generated batche into n seperate files so every worker can get his own unique file of training-batches

**Comment by dmt93** [comment]
Using the flag --num_batch_files="#" you can create # number of training batch files. They should be named "batches_#.tfrecord" 
\# ... starting from 0
Maybe we should create a separate folder for the batches?
Couldn't test the train mechanism because I don't have a docker infrastructure now.

**Comment by dbaumgarten** [comment]
Sounds good.
I don't think separate folders would be helpful but instead just complicate stuff.
In a distributed setup the user will have to specify individual flags for each worker. Adding --batch_file should not be too much of a problem.

Btw. "hotfix" is not a terribly helpful commit message ;)
(Mentioning 2dd13938e331b99913e32a48e343eb8e9b51b3b6 to link it with this Issue.)

**Comment by dbaumgarten** [comment]
I just noticed your changes broke the default_value for --batches_file.

**Comment by dbaumgarten** [comment]
@dmt93 would you please fix the default value for --batches_file. This bug breaks the example-code and the docker-compose setup.

**Comment by dmt93** [comment]
@dbaumgarten you need to check the compose part

**Comment by dbaumgarten** [comment]
Seems like everything is now working as intended :+1:
