### ISSUE TITLE
TF record could not be created with preprocessing

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [dbaumgarten/FToDTF#40]
Hey, I cloud not reproduce your code. 

I did the following:

`fasttext preprocess --corpus_path example.txt`

and when I looked at the create batches.tfrecord, it was empty.

`du -h batches.tfrecord`
Outputs:
`0B	batches.tfrecord`

This is the text file containing one sentence. (Also tried this with bigger text files.)
[example.txt](https://github.com/dbaumgarten/FToDTF/files/2265506/example.txt)

**Comment by dbaumgarten** [comment]
The example text your are using is to small. It is not even enough to create a single trainings-batch.
The default batch-size is 128. Also the subsampling will drop the most common words and with that few words every word is common (in your example each word makes up 25% of the corpus.)

To make your example-text work you would need to run the preprocess like:
```
fasttext preprocess --corpus_path ~/Downloads/example.txt --batch_size 1 --rejection_threshold 1
```
But please note that that amount of training data will not provide usefull results.
Could you link the one of these bigger test-files? I would guess they are still not big enough.

But I think it would certainly make sense to display an error-message when trying to generate batches from a too small amount of data.
