### ISSUE TITLE
Q: skipgram?

### ISSUE THREAD

**Issue by GeorgesAlkhouri** [dbaumgarten/FToDTF#41]
Are you sure you implemented the skipgram model?

Because your features look like this:

`[[138233, 147057, 70344, 42249], [56281, 105661, 178063, 107522]] `

and your labels like this

`[7, 5]`

So, you are predicting the target word (label) in condition to the context words (feature). This is CBOW not skipgram.

Or am I missing something?

**Comment by dbaumgarten** [comment]
We have indeed implemented the Skipgram-Model
The features are the hashes of the target-word-ngrams (each of the 4 numbers in your feature entry example is 1 ngram of the target word) and the label is the expected context word.

Sentence: Peter Lustig
Target-word: Peter
Context-Word: Lustig
Target-Ngrams: [*pe, pet, ete, ter, er*]
Hashes of ngrams : [227,145,222,456,666]
Dictionary-Index of Context-Word: 42
Complete Training sample:
Features:  [227,145,222,456,666], Label: 42

**Comment by GeorgesAlkhouri** [comment]
Yes you are right. I got confused with the binary context word classification.  I read the paper again. Now it is clear
